title: "Lizberries Blog"
description: "Novità, dietro le quinte e curiosità dal mondo Lizberries"
url: "https://blog.lizberries.thelizards.it"
author:
  name: "Lizberries Team"
  email: "lizberries@thelizards.it"
theme: minima
show_excerpts: true
lang: it_IT

# Impostazioni di paginazione
paginate: 5
paginate_path: "/page:num/"

sass:
  style: compressed

plugins:
  - jekyll-paginate

# Default settings
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      image: "/assets/images/The-Lizberries-Logo_small.png"
      layout: post
      lang: "it"

#test
